default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: ermeltech_saas_development

test:
  <<: *default
  database: ermeltech_saas_test
